### ISSUE TITLE
Rethinking 2 - Chapter 4 - Code 4.61 Plots not on same canvas

### ISSUE THREAD

**Issue by gabipana7** [pymc-devs/resources#130] opened 2020-12-07 15:55 UTC
The arviz plots here:
`plt.scatter(d2.weight, d2.height)
az.plot_hpd(weight_seq, mu_pred.T)
az.plot_hpd(d2.weight, height_pred["height"])
plt.plot(weight_seq, mu_mean, "k")
plt.xlabel("weight")
plt.ylabel("height")
plt.xlim(d2.weight.min(), d2.weight.max());`
Do not output on the same figure as you have in your notebook. In my notebook everythime I call an az.plot_hdp ( changed to az.plot_hdi ) it goes into another, separate plot ! How do I show everything on top of eachother as you have ? 
![Screenshot from 2020-12-07 17-54-29](https://user-images.githubusercontent.com/72228598/101373165-53237200-38b5-11eb-82b0-690eb65fe82d.png)

**Comment by gabipana7** [comment] 2020-12-07 15:59
Nevermind, I found out how to do it, after hours of searching
`ax = az.plot_hdi(d2.weight, height_pred["height"])
az.plot_hdi(weight_seq, mu_pred.T, ax=ax)`
So you just add the 'ax=' on the first one, and add ax=ax to the second one, if anyone else has the problem. I don't know why it works, but it works !

**Comment by aloctavodia** [comment] 2020-12-07 16:45
Thanks for reporting this. The issue is related to arviz-devs/arviz#1452. In previous versions, ArviZ automatically got the axes, but then we made a change that requires users to manually pass the axes. Once the mentioned issue gets merged this will be the case again. So I am keeping this issue open until that.

**Closed** 2020-12-08 11:07 UTC
